### ISSUE TITLE
QGIS stürzt ohne Crash-Meldung ab, wenn man versucht, etwas zu laden

### ISSUE THREAD

**Issue by danceb** [EZUSoft/SaxonyCadastralParcels#1]
Ein Einbinden der Flurstücke in QGIS ist nicht möglich. Bei dem Versuch stürzt QGIS hart ohne jede Crash-Meldung ab.
Getestet mit QGIS 3.18 und 3.22.

**Comment by EZUSoft** [comment]
Ich habe  soeben mit QGIS 3.18.2 unter Windows getestet. Läuft problemlos. 
Das PlugIn selbst wird recht rege genutzt, es gab bisher keine diesbezüglichen Fehlermeldungen. Ich vermute deshalb eher Probleme bei deiner QGIS-Installation.

**Comment by danceb** [comment]
Ok, danke für die fixe Rückmeldung und das Testen! Ich schaue mal, woran es bei uns liegen könnte.

**Comment by EZUSoft** [comment]
Bitte setze mich kurz in Kenntnis, wenn/wie du das Problem lösen konntest.

**Comment by danceb** [comment]
Also das Problem wurde schon gefunden, aber noch nicht gelöst. Die Netzwerk-Firewall blockt wohl den Download der Zip-Archive. Da das für das Plugin aber wohl was anderes ist, als wenn "nur" keine Internetverbindung besteht, gibt es keine ensprechende Rückmeldung sondern den Absturz. Liegt also an unserer Netzwerk-Konfiguration.
Wobei das Plugin evtl. dahingehend verbessert werden könnte, dass in so einem Fall eine Fehlermeldung kommt aber QGIS nicht abstürzt.

**Comment by danceb** [comment]
Hallo, nochmal ein Update hierzu: Wir konnten das Problem weiter eingrenzen und reproduzieren. 

Der Download funktioniert bei uns im Netzwerk nur, wenn man **beide** Gemarkungskataloge für Sachsen und Thüringen herunterlädt. Also im Drowdown-Menü sowohl einmal "Land Sachsen" und einmal "Land Thüringen" auswählt. Wenn ich direkt nur "Land Sachsen" oder "Land Thüringen" auswähle, dann kommt es zu dem QGIS-Absturz.

Auf einem PC außerhalb des Netzwerkes funktioniert es jedoch richtig und wie erwsrtet, auch wenn ich nur ein Bundesland auswähle.

Was macht das Plugin an dieser Stelle, wenn man das Bundesland auswählt? Oder eine Andere Idee, woran das liegen könnte? Vielleicht können wir mit einigen Tipps die Ursache weiter eingrenzen. Vielen Dank!

**Comment by EZUSoft** [comment]
Hallo Daniel,
Dank für die Rückantwort.
**Ich habe momentan keine Idee wie ich das Ganze nachstellen soll.** Das Blocken der ZIP-Archive durch die FW war ja wohl nicht die Ursache. Das hätte ich vielleicht noch simulieren können.

Ich kann nur die Fehlerprotokollierung erweitern, welche im Moment ohnehin nicht so toll ist.  Da ich allerdings nicht weiß an welcher Stelle der Absturz erfolgt wird das recht aufwändig. 
Das QGIS selbst abstürzt ist leider auch eher ein Zeichen für QGIS-Probleme, denn ein  PlugIN darf keinen QGIS-Absturz auslösen!

**Comment by danceb** [comment]
Ein Update hierzu: Nach langer Zeit mit der aktuellen QGIS LTR Version 3.34 nochmal getestet und es funktioniert nun! Woran es jetzt nun lag, kann ich rückblickend nicht mehr sagen, aber irgendwo (bei uns im Netzwerk oder in Zusammenhang mit QGIS) wurde die Ursache behoben.
