### ISSUE TITLE
Please add an English description of the plugin

### ISSUE THREAD

**Issue by pcav** [EZUSoft/SaxonyCadastralParcels#1]
So many users will be able to understand more easily whether they need it.
Thanks.

**Comment by EZUSoft** [comment]
Thanks for the hint. I have changed it.

**Comment by EZUSoft** [comment]
You have not yet approved the current version. Are there any problems?
[](http://plugins.qgis.org/plugins/SaxonyCadastralParcels/version/0.2.1/)
