### ISSUE TITLE
Python Error when importing as DXF

### ISSUE THREAD

**Issue by schorsch2** [EZUSoft/SaxonyCadastralParcels#2]
I am trying to import boundaries from Saxony and save them as dxf. Unfortunately, I get this error message:

`Ein Fehler trat bei der Ausführung von Python-Code auf: 

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/wei/AppData/Local/Temp/{D5E6A1F8-392F-4241-A0BD-5CED09CFABC7}/96cfa72f-24a9-45d9-806c-602082916061_1.csv' 
Traceback (most recent call last):
  File "C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaxonyCadastralParcels\uiFlurst4BL.py", line 346, in btnStart_clicked
    Antw = GemWorker (self, self.glAktLandKenn, self.fncAktLandName(), Liste, ZielPfad, self.chkSHP.isChecked(), self.chkDXF.isChecked(),self.chkMergeFlur.isChecked())
  File "C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaxonyCadastralParcels\clsWorker.py", line 488, in GemWorker
    genDXF4Gemarkung (uiParent, unzipdir, shpList, expPfad + datZeile[idxLokName] + '.dxf')
  File "C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaxonyCadastralParcels\clsWorker.py", line 324, in genDXF4Gemarkung
    concatDXFBeschriftung(qDxfDat,qCsvDat,zDxfDat,sDat)
  File "C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaxonyCadastralParcels\clsWorker.py", line 589, in concatDXFBeschriftung
    csvArray = fncUniDatReadAll23(qCsvDat,'utf-8')  # Utf8-Datei
  File "C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaxonyCadastralParcels\fnc4all.py", line 394, in fncUniDatReadAll23
    tmp = open(DatName, "r", encoding=sEncode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/wei/AppData/Local/Temp/{D5E6A1F8-392F-4241-A0BD-5CED09CFABC7}/96cfa72f-24a9-45d9-806c-602082916061_1.csv'

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.18.2-Zürich Zürich, 515138c171 

Python-Pfad:
C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/OSGEO4~1/apps/qgis/./python
C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\Users\wei\AppData\Roaming\Python\Python37\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2mapillary
C:\Users\wei\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2mapillary\extlibs`

**Comment by AliHaider20** [comment]
As I see most of them are FileNotFoundError. That means the path given by you is wrong.

**Comment by schorsch2** [comment]
The file 96cfa72f-24a9-45d9-806c-602082916061_1.csv apparently does not exist. The rest of the path exists and is apparently assigned by QGIS. The path for the DXF files also exists and is writable.

**Comment by AliHaider20** [comment]
Yeah, but as the first line is giving an error the below lines are not going to run. It's not like C.

**Comment by schorsch2** [comment]
The question is: how to fix the problem?

**Comment by AliHaider20** [comment]
If the file which you mentioned doesn't exits on the system the code won't run. 
Also even if it exists still it won't runs cause it has hipens (-) in it. U need to use raw string.

**Comment by schorsch2** [comment]
This *.csv - file is not created by me. The extension "SaxonyCadastralParcels" should create it itself and uses it in a later step.

**Comment by EZUSoft** [comment]
Have you tried an older version of QGIS?

**Comment by schorsch2** [comment]
Yes, in earlier versions the extension worked well. I just can't say from when it stopped running.

**Comment by EZUSoft** [comment]
Ok I install the new version and test with it ...

**Comment by EZUSoft** [comment]
It is a bug / problem of the 18.2. Version 18.1 works.
I'll see if I can work around the problem.
Until then you have to work with the old version or use our program [http://gis.makobo.de/geotkf/] under Windows).

**Comment by schorsch2** [comment]
Thanks for the fast response!

**Comment by EZUSoft** [comment]
Version 0.3.3 should solve the problems with QGIS 3.18.2.

**Comment by schorsch2** [comment]
Works!

**Comment by schorsch2** [comment]
Sorry, where are the dxf- files? Can not find them inside the directory.

**Comment by EZUSoft** [comment]
Sorry, but there are probably a few more problems :-(

**Comment by EZUSoft** [comment]
Version 0.3.4 should solve (all) the problems.

**Comment by schorsch2** [comment]
Working again!
