### ISSUE TITLE
Plugin Funktioniert nicht mehr

### ISSUE THREAD

**Issue by EnkiKudo** [EZUSoft/SaxonyCadastralParcels#2]
Durch eine Änderung der Sicherheitseinstellungen können unsere Programme nicht mehr auf HTTP zugreifen, sondern nur noch auf HTTPS. Welche Dateien muss man alles abändern, damit es wieder funktioniert wie es soll?

**Comment by EZUSoft** [comment]
Ich kann dein Problem nicht nachvollziehen. Bei mir funktioniert sowohl Sachsen als auch Thürigen.
Hast du die aktuelle Version des PlugIN
![Screenshot 2024-01-18 104704](https://github.com/EZUSoft/SaxonyCadastralParcels/assets/19267407/004993d8-8b23-4158-9145-fb063ecfbec1)

**Comment by EZUSoft** [comment]
So ein ... :-(
Ich habe dir mal eine angepasste Vorab-Version hochgeladen:
[https:///makobo/makobo.de/data/SaxonyCadastralParcels.zip](url)

**Comment by EZUSoft** [comment]
So ein ... :-(
Ich habe dir mal eine angepasste Vorab-Version hochgeladen:
https://makobo.de/data/SaxonyCadastralParcels.zip

**Comment by EnkiKudo** [comment]
Ich danke. Jetzt funktioniert es fürs erste wieder. Mal sehen was sich unsere IT als nächstes einfallen lässt :D
